### ISSUE TITLE
functional pseudo class's argument formatting 

### ISSUE THREAD

**Issue by anikethsaha** [anikethsaha/style-perfectionist#10]
### Input
```css
a:not(
:hover
) {
  text-decoration: none;
}

```

### Currently

```css
a:not(
:hover
) {
    text-decoration: none;
}

```

### It should be 

```css
a:not(:hover) {
  text-decoration: none;
}

```
